apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  selector:
    app: mlflow
  type: NodePort  # Ensures it's accessible outside the cluster
  ports:
    - protocol: TCP
      port: 80             # Internal Cluster Port
      targetPort: 5000     # Matches the MLflow container port
      nodePort: 30080      # Fixed External Port (Pick between 30000-32767)

