apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: mlflow:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        command: ["mlflow", "ui", "--host", "0.0.0.0", "--port", "5000"]

